test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,6 +31,10 @@ jobs:
         run: |
           terraform apply -auto-approve
           CLEAN_IP=$(terraform output -raw instance_public_ip | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
+          if [[ -z "$CLEAN_IP" ]]; then
+            echo "ERROR: Extracted IP is empty!"
+            exit 1
+          fi
           echo "EC2_IP=$CLEAN_IP" >> $GITHUB_ENV
           echo "EC2 IP: $CLEAN_IP"
         working-directory: terraform
